stages:
  - build
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet publish ./api -c Release -o publish
  artifacts:
    paths:
      - publish/
    expire_in: 1 hour
  only:
    - develop
    - main

deploy_main:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - echo "Unzipping the artifacts..."
    - unzip artifacts.zip -d .
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    - az webapp deploy --resource-group djoufson-learnings --name over-engineered-todo-list --src-path ./publish --type zip
  only:
    - main
  dependencies:
    - build
