stages:
  - build
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  script:
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet publish ./api -c Release -o output
  artifacts:
    paths:
      - output/
    expire_in: 1 hour
  only:
    - develop
    - main

deploy_main:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Install necessary packages (Python, pip, and zip)"
    - apk update && apk add --no-cache py3-pip gcc musl-dev python3-dev libffi-dev openssl-dev cargo make zip
    - python3 -m venv /venv
    - source /venv/bin/activate
    - pip install --upgrade pip
    - pip install azure-cli
    - echo "Compress and deploy the app"
    - cd output && zip -r ../deploy.zip . && cd ..
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    - az webapp deploy --resource-group djoufson-learnings --name over-engineered-todo-list --src-path deploy.zip --type zip
  only:
    - main
  dependencies:
    - build
